import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { FormEvent, useEffect, useState } from "react";
import { getLocations, requestPrediction } from "./api/predictionClient";
import type { PredictionInput, PredictionResult } from "./types/prediction";
import "./styles.css";

const defaults: PredictionInput = { location:"", carpet_area_sqft:0, floor_num:0, bathroom:1, balcony:0, car_parking:0, furnishing:"Semi-Furnished", transaction:"Resale", ownership:"Freehold", facing:"East" };
const choices = { furnishing:["Furnished","Semi-Furnished","Unfurnished"], transaction:["New Property","Resale"], ownership:["Freehold","Leasehold","Unknown"], facing:["East","West","North","South","Unknown"] };

function HomePage() {
  const navigate = useNavigate(); const [form,setForm] = useState(defaults); const [locations,setLocations] = useState<string[]>([]); const [error,setError] = useState(""); const [loading,setLoading] = useState(false);
  useEffect(() => { getLocations().then(setLocations).catch(() => setError("Could not load locations. Start the backend and refresh.")); }, []);
  const update = (key: keyof PredictionInput, value: string) => setForm({...form,[key]: ["carpet_area_sqft","floor_num","bathroom","balcony","car_parking"].includes(key) ? Number(value) : value});
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.location || form.carpet_area_sqft <= 0) { setError("Choose a location and enter an area greater than zero."); return; } setError(""); setLoading(true); try { const result = await requestPrediction(form); navigate("/result", {state:result}); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong."); } finally { setLoading(false); } }
  return <main><header><p className="eyebrow">PROPERTY ESTIMATOR</p><h1>A practical price check before you shortlist.</h1><p>Enter the basics of a home and get an estimated listing price in Indian rupees.</p></header><form onSubmit={submit}><label>Location<select required value={form.location} onChange={e=>update("location",e.target.value)}><option value="">Select a location</option>{locations.filter(x=>x!=="other").map(x=><option key={x}>{x}</option>)}</select></label><div className="grid"><label>Carpet area (sq ft)<input type="number" min="1" required value={form.carpet_area_sqft||""} onChange={e=>update("carpet_area_sqft",e.target.value)}/></label><label>Floor<input type="number" min="-1" value={form.floor_num} onChange={e=>update("floor_num",e.target.value)}/></label><label>Bathrooms<input type="number" min="0" value={form.bathroom} onChange={e=>update("bathroom",e.target.value)}/></label><label>Balconies<input type="number" min="0" value={form.balcony} onChange={e=>update("balcony",e.target.value)}/></label><label>Car parking<input type="number" min="0" value={form.car_parking} onChange={e=>update("car_parking",e.target.value)}/></label></div><div className="grid">{Object.entries(choices).map(([key,values])=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<select value={form[key as keyof typeof choices] as string} onChange={e=>update(key as keyof PredictionInput,e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>)}</div>{error && <p className="error">{error}</p>}<button disabled={loading}>{loading ? "Calculating..." : "Estimate price"}</button></form></main>;
}

function ResultPage() { const result = useLocation().state as PredictionResult | undefined; if (!result) return <main><p>No estimate yet.</p><Link to="/">Start again</Link></main>; return <main className="result"><p className="eyebrow">YOUR ESTIMATE</p><h1>{new Intl.NumberFormat("en-IN", {style:"currency",currency:"INR",maximumFractionDigits:0}).format(result.predicted_price)}</h1><p>This is a model estimate, not a valuation. Compare it with recent listings before making a decision.</p><Link className="button" to="/">Check another home</Link></main> }
function NotFound() { return <main><h1>That page does not exist.</h1><Link to="/">Back to estimator</Link></main> }
export default function App(){ return <BrowserRouter><Routes><Route path="/" element={<HomePage/>}/><Route path="/result" element={<ResultPage/>}/><Route path="*" element={<NotFound/>}/></Routes></BrowserRouter> }
